import { randomUUID } from 'node:crypto'
import { Hono } from 'hono'
import { zv } from '@/server/routes/validator'
import { z } from 'zod'
import { listActiveSessions, listDeletedSessions } from '@/lib/session/list'
import { getSessionDetail, getSessionBlockedHosts, getSessionPrompt } from '@/lib/session/detail'
import { deleteSession } from '@/lib/session/delete'
import { restartSession } from '@/lib/session/restart'
import { createSession, type SessionCreateOptions } from '@/server/session-create'
import { tryClaimPrewarmed } from '@/server/prewarm'
import { getDefaultTool } from '@/lib/project/preferences'
import { registerProvisioning, removeProvisioning } from '@/server/provisioning'
import { streamProvisioned } from '@/server/routes/provisioned-stream'
import { ServerError } from '@/shared/errors'
import { allowSessionHost } from '@/lib/session/allow-host'
import { resolveSessionContainer } from '@/server/session-resolve'
import { pickNextStreamSession } from '@/server/stream-picker'
import { notifySessionListChanged } from '@/server/sessions-changed'
import { createShellWindow, listSessionTerminals, killWindowTerminal } from '@/server/terminals'
import { setSessionTitle } from '@/lib/session/titles'

export const sessionApp = new Hono()
  .get(
    '/list',
    zv('query', z.object({ project: z.string().optional() })),
    async (c) => {
      const { project } = c.req.valid('query')
      return c.json(await listActiveSessions(project || undefined))
    },
  )
  .get(
    '/list-deleted',
    zv('query', z.object({
      project: z.string().optional(),
      limit: z.coerce.number().int().positive().optional(),
    })),
    async (c) => {
      const { project, limit } = c.req.valid('query')
      return c.json(await listDeletedSessions(project || undefined, limit))
    },
  )
  .post(
    '/create',
    zv('json', z.object({
      project: z.string().min(1),
      // Pre-generated by the webapp so the provisioning row is selectable and
      // reload-matchable before any round-trip; the CLI omits it and the
      // server mints one.
      sessionId: z.string().uuid().optional(),
      addDir: z.array(z.string()).optional(),
      addDirRw: z.array(z.string()).optional(),
      tool: z.enum(['claude', 'codex', 'opencode']).optional(),
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      const sessionId = body.sessionId ?? randomUUID()
      return streamProvisioned(c, sessionId, async (onProgress) => {
        // Resolve the tool server-side: explicit --tool wins, else the
        // configured default (yaac tool set), else claude. This is the tool the
        // prewarm pool warms, so a bare create matches its spare.
        const tool = body.tool ?? (await getDefaultTool()) ?? 'claude'

        // Fast path: claim a prewarmed spare for this project + tool. Skipped
        // when --add-dir is requested (the spare lacks those mounts). A claim
        // returns the spare's own id and registers no provisioning row — the
        // unhidden session lists in the very next snapshot.
        if (!body.addDir?.length && !body.addDirRw?.length) {
          const claimed = await tryClaimPrewarmed(body.project, tool, body.gitUser, onProgress)
          if (claimed) return claimed
        }

        const opts: SessionCreateOptions = {
          sessionId,
          onProgress,
          tool, // resolved default applies when --tool was omitted
        }
        if (body.addDir) opts.addDir = body.addDir
        if (body.addDirRw) opts.addDirRw = body.addDirRw
        if (body.gitUser) opts.gitUser = body.gitUser
        // Register before the long await so the row shows up instantly and
        // survives a browser reload (the stream keeps running server-side).
        registerProvisioning({ sessionId, projectSlug: body.project, tool, kind: 'create' })
        return await createSession(body.project, opts)
      })
    },
  )
  .post(
    '/restart',
    zv('json', z.object({
      sessionId: z.string().min(1),
      // The webapp passes the session's project + tool (known from the deleted
      // entry) so the provisioning row can render while restart resolves the
      // target authoritatively. The CLI omits them — it doesn't need the row.
      projectSlug: z.string().optional(),
      tool: z.enum(['claude', 'codex', 'opencode']).optional(),
      addDir: z.array(z.string()).optional(),
      addDirRw: z.array(z.string()).optional(),
      gitUser: z.object({ name: z.string(), email: z.string() }).optional(),
    })),
    (c) => {
      const body = c.req.valid('json')
      if (body.projectSlug) {
        registerProvisioning({
          sessionId: body.sessionId,
          projectSlug: body.projectSlug,
          tool: body.tool ?? 'claude',
          kind: 'restart',
        })
      }
      return streamProvisioned(c, body.sessionId, (onProgress) =>
        restartSession(body.sessionId, {
          addDir: body.addDir,
          addDirRw: body.addDirRw,
          gitUser: body.gitUser,
          onProgress,
        }))
    },
  )
  .post(
    '/delete',
    zv('json', z.object({ sessionId: z.string().min(1) })),
    async (c) => {
      const { sessionId } = c.req.valid('json')
      const info = await deleteSession(sessionId)
      return c.json(info)
    },
  )
  .post('/provisioning/:id/dismiss', (c) => {
    // Drop a provisioning entry (only meaningful for a failed one — successful
    // ones self-clean once the real session lists). Idempotent for any id.
    removeProvisioning(c.req.param('id'))
    return c.body(null, 204)
  })
  .post(
    '/stream/next',
    zv('json', z.object({
      project: z.string().optional(),
      tool: z.enum(['claude', 'codex', 'opencode']).optional(),
      visited: z.array(z.string()).default([]),
      lastVisited: z.string().optional(),
      lastProjectSlug: z.string().optional(),
      lastTool: z.enum(['claude', 'codex', 'opencode']).optional(),
      lastOutcome: z.enum(['detached', 'closed_blank', 'closed_prompted', 'none']).default('none'),
    })),
    async (c) => {
      const body = c.req.valid('json')
      const result = await pickNextStreamSession(body)
      return c.json(result)
    },
  )
  .post(
    '/:id/title',
    zv('json', z.object({ title: z.string().max(500) })),
    async (c) => {
      // Resolve in any state — renaming a waiting or just-stopped session is
      // fine; the title lives on the host, not in the container.
      const { projectSlug, sessionId } = await resolveSessionContainer(c.req.param('id'))
      await setSessionTitle(projectSlug, sessionId, c.req.valid('json').title)
      // Push a fresh snapshot so the sidebar reflects the rename immediately.
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  .get('/:id/terminals', async (c) => {
    const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await listSessionTerminals(jobName))
  })
  // Create a scratch-shell window in the session's `yaac` tmux session,
  // returning its entry so the client can open a pane immediately.
  .post('/:id/terminals', async (c) => {
    const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
    return c.json(await createShellWindow(jobName))
  })
  .post(
    '/:id/terminals/close',
    zv('json', z.object({ target: z.string().min(1) })),
    async (c) => {
      const { jobName } = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      const { target } = c.req.valid('json')
      try {
        await killWindowTerminal(jobName, target)
      } catch (err) {
        throw new ServerError('VALIDATION', err instanceof Error ? err.message : String(err))
      }
      return c.body(null, 204)
    },
  )
  .get('/:id', async (c) => c.json(await getSessionDetail(c.req.param('id'))))
  .get('/:id/blocked-hosts', async (c) => c.json(await getSessionBlockedHosts(c.req.param('id'))))
  // Allow a previously-blocked host (webapp click-to-allow). The proxy prunes
  // the host from its recorded blocked set, so the snapshot we push clears the
  // badge. Persist/fan-out policy lives in allowSessionHost.
  .post(
    '/:id/allow-host',
    zv('json', z.object({
      // A bare hostname or wildcard pattern — the grammar hostMatchesPattern
      // (default-allowed-hosts.ts) matches against; no scheme/path/port.
      host: z.string().regex(/^[A-Za-z0-9*._-]+$/, 'host must be a bare hostname or *.wildcard pattern'),
      persist: z.boolean().optional(),
    })),
    async (c) => {
      const { host, persist } = c.req.valid('json')
      const target = await resolveSessionContainer(c.req.param('id'), { requireRunning: true })
      await allowSessionHost(target, host, { persist: persist ?? false })
      notifySessionListChanged()
      return c.body(null, 204)
    },
  )
  .get('/:id/prompt', async (c) => {
    const prompt = await getSessionPrompt(c.req.param('id'))
    return c.json({ prompt: prompt ?? '' })
  })
