import { kubectlApply, kubectlWithRetry } from '#lib/k8s/kubectl'

/**
 * A minimal, permissive (`x-kubernetes-preserve-unknown-fields`) CRD for one
 * Cilium type. The inner (nested) yaac installs these into its OWN vcluster so
 * its `ensureProxyResources` CEC/CNP applies validate and persist — it owns its
 * vcluster, exactly as the outer yaac's setup installs Cilium on the host.
 *
 * Permissive (not Cilium's full ~400KB CNP schema) on purpose: in a vcluster
 * there is no Cilium datapath, so these objects are INERT — the outer server
 * projects the real, host-enforced redirect (docs/yaac-in-yaac-inner-egress.md).
 * They exist only so the inner yaac's apply succeeds and it can read its own
 * policy back; the objects are generated by yaac's own builders, so they are
 * well-formed by construction and need no API-server schema validation.
 */
function permissiveCiliumCrd(p: {
  plural: string
  singular: string
  kind: string
  listKind: string
  shortNames: string[]
  categories: string[]
}): Record<string, unknown> {
  return {
    apiVersion: 'apiextensions.k8s.io/v1',
    kind: 'CustomResourceDefinition',
    metadata: { name: `${p.plural}.cilium.io` },
    spec: {
      group: 'cilium.io',
      scope: 'Namespaced',
      names: {
        kind: p.kind,
        listKind: p.listKind,
        plural: p.plural,
        singular: p.singular,
        shortNames: p.shortNames,
        categories: p.categories,
      },
      versions: [{
        name: 'v2',
        served: true,
        storage: true,
        schema: { openAPIV3Schema: { type: 'object', 'x-kubernetes-preserve-unknown-fields': true } },
      }],
    },
  }
}

export function buildCiliumEnvoyConfigCrdManifest(): Record<string, unknown> {
  return permissiveCiliumCrd({
    plural: 'ciliumenvoyconfigs',
    singular: 'ciliumenvoyconfig',
    kind: 'CiliumEnvoyConfig',
    listKind: 'CiliumEnvoyConfigList',
    shortNames: ['cec'],
    categories: ['cilium'],
  })
}

export function buildCiliumNetworkPolicyCrdManifest(): Record<string, unknown> {
  return permissiveCiliumCrd({
    plural: 'ciliumnetworkpolicies',
    singular: 'ciliumnetworkpolicy',
    kind: 'CiliumNetworkPolicy',
    listKind: 'CiliumNetworkPolicyList',
    shortNames: ['cnp', 'ciliumnp'],
    categories: ['cilium', 'ciliumpolicy'],
  })
}

/**
 * Install the Cilium CEC/CNP CRDs (the nested yaac's own vcluster) and wait for
 * them to be Established, so a CEC/CNP apply right after doesn't race the API
 * server registering the new types ("no matches for kind").
 */
export async function ensureCiliumCrds(): Promise<void> {
  await kubectlApply(buildCiliumEnvoyConfigCrdManifest())
  await kubectlApply(buildCiliumNetworkPolicyCrdManifest())
  await kubectlWithRetry([
    'wait', '--for=condition=Established', '--timeout=60s',
    'crd/ciliumenvoyconfigs.cilium.io', 'crd/ciliumnetworkpolicies.cilium.io',
  ])
}
